name: Build Vena Studio Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Packages
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release -v

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: VStudio
          path: build/windows/x64/runner/Release
